In [4]:
import pandas as pd

In [ ]:
#Code that extracts the data we use from a much larger dataset that comes from here https://git.nomics.world/dbnomics-source-data/cepii-source-data/-/blob/master/TRADE/trade_chel_YYYYMMDD.csv
"""
trade=pd.read_csv('trade_data.csv', usecols=['exporter', 'importer', 'secgroup', 'product', 'v2020'], sep=';')
trade_undifferenciated=trade[trade['product']=='TT']
trade_undifferenciated=trade_undifferenciated[['exporter','importer','secgroup','product','v2020']]
trade_undifferenciated.to_csv('Data_exports.csv')
"""

In [35]:
data=pd.read_csv('Data_exports.csv', index_col=0)

In [36]:
data

      exporter importer secgroup product          v2020
0          AES      AES      CAT      TT  227476.045916
1          AES      AFA      CAT      TT    1437.590947
2          AES      AFN      CAT      TT    5408.519442
3          AES      AFR      CAT      TT   47568.935618
4          AES      AFS      CAT      TT   16271.739595
...        ...      ...      ...     ...            ...
19316      YUG      VEN      CAT      TT       1.633391
19317      YUG      VNM      CAT      TT     114.547872
19318      YUG      WLD      CAT      TT   85068.226420
19319      YUG      XXX      CAT      TT     132.854201
19320      YUG      YUG      CAT      TT   17194.157859

[19321 rows x 5 columns]

In [41]:
code_country= pd.read_csv('country_codes_3.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 3354: invalid continuation byte

In [40]:
code_country

    country_code,"country_name_abbreviation","country_name_full","iso_2digit_alpha","iso_3digit_alpha"
0             4,"Afghanistan","Afghanistan","AF","AFG"
1                     8,"Albania","Albania","AL","ALB"
2                    12,"Algeria","Algeria","DZ","DZA"
3      16,"American Samoa","American Samoa","AS","ASM"
4                    20,"Andorra","Andorra","AD","AND"
..                                                 ...
222  876,"Wallis and Futuna Isds","Wallis and Futun...
223                     882,"Samoa","Samoa","WS","WSM"
224                     887,"Yemen","Yemen","YE","YEM"
225  891,"Serbia and Montenegro","Serbia and Monten...
226                   894,"Zambia","Zambia","ZM","ZMB"

[227 rows x 1 columns]